### ISSUE TITLE
Home Page -- Basic redesign to address multiple design improvements

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/chicago-environment-explorer#115]
**Issue**

We currently have 5 tickets for Home Page design that affect each other enough to be addressed in a single effort. I'm closing those individual tickets in favor of this one, and incorporating all of their points into the summary below. I think that whenever this task is taken on, a simple, single mockup/reconfiguration of the home page would be the best way to solve everything all at once.

- [x] #89 Issue: Title text does not stand out aesthetically
    Recommendation: Change title’s prominent text to accent color and bold the important keywords, keep paragraph text close to title text
    Rationale: Draw more attention to the headlining content

- [x] #90 Issue: Is the order (i.) Community Report, (ii.) Neighborhood map, (iii.) Resource Guide, on the website in descending order of click-through?
    Recommendation: Consider reordering in descending order as per data from Google Analytics or similar
    Rationale: Users scan pages in Z and F patterns, keeping most used pages from left to right is preferred

- [x] #91 Issue: Is the neighborhood map the most used feature?
    Recommendation: Promote the neighborhood location search bar to search for a location or zip code but also give an option to see all locations if the user does not want to type in anything specific
    Rationale: Users can quickly query for the map they want to search instead of scrolling down

- [x] #92 Issue: The jumbotron could be more visually engaging.
    Recommendation: The page’s second section with the map previews showing PM2.5, vegetation, biodiversity, traffic, redlining, and asthma could be placed on the right side of the first section, beside the heading “Uncover the nature of Chicago's environment.
    Rationale: Visuals can improve the overall aesthetic attractiveness of the landing page

- [x] #93 Issue: In the contributors carousel, contributor logos does not partially peek when rolling from right to left
    Recommendation: When contributor logos show from right to left, let it smoothly and partially peek in
    Rationale: Feels more continuously flowing than abruptly showing the full logo

I don't personally think this requires a _radical_ redesign of the page or anything, mostly just a reconfiguration.

**Comment by Makosak** [comment]
These are integrating and updated at a working version: https://deploy-preview-201--chicago-env-explorer.netlify.app/

@bodom0015 may need some help with final formatting pieces, but really close! @shubhamk008 thoughts?

**Comment by shubhamk008** [comment]
These issues look addressed
